repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: run-eslint
        name: Run ESLint for JS files
        entry: ./pre-commit-scripts/check-eslint.sh
        language: script
        files: \.js$
      - id: check-format
        name: Format code with Black
        entry: ./pre-commit-scripts/check-format.sh
        language: script
        files: \.py$
      - id: run-tests
        name: Run unit tests
        entry: ./pre-commit-scripts/check-unit-tests.sh
        language: script
